### ISSUE TITLE
Game crashes when i try to upgrade my troops

### ISSUE THREAD

**Issue by OfficialKitkat** [Hirtol/PartyScreenEnhancements#4]
Hello. Im new to the whole modding thing and just downloaded my first mods. Tryed to upgrade my troops after they leveld up and the game crashed as fast and a choose what they were gonna be upgraded to. I dont know how to fix it and have no idea if this mod is what caused it. But sent it to another community and they told me they think PartyScreen was the reason. Ill send you a picture of the msg i got and also the mods im using.
![5a06ad50e2a120ade7d9e902fa08274e](https://user-images.githubusercontent.com/67970177/86820562-85703f80-c089-11ea-8613-4c55b0cd0c57.png)
![c49895b99c13d66fe1eab38663b184e9](https://user-images.githubusercontent.com/67970177/86820746-bfd9dc80-c089-11ea-9ab0-67bb5a4a7367.png)

I dont know how to send a saved game tho. But to give a bit more info i made a new campain and saved it. then loaded it to make sure it worked. then played for 15-20 min before i wanted to upgrade my troops and it crashed

**Comment by Hirtol** [comment]
Which version of the game are you using? I assume 1.4.0 or 1.4.1?

The error looks like the error you'd get if one of your mods hasn't been updated past 1.3, so I'd ask you ensure all your mods (including Party Screen Enhancements) is updated to their latest version and also check that they're compatible with the game version you're using.

The latest version for PSE is available here on Github:
https://github.com/Hirtol/PartyScreenEnhancements/releases/tag/v1.5.2

If it still crashes after you've ensured the aforementioned then I'd appreciate the save game if you could provide it.

Thanks!
